services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cobweb-local-backend
    ports:
      - "8080:8080"
    env_file: "./backend/.env"
    networks:
      - cobweb-network
    develop:
      watch:
        - action: rebuild
          path: ./backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cobweb-local-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080/api
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: rebuild
          path: ./frontend/package.json
          target: /app/package.json
    depends_on:
      - backend
    networks:
      - cobweb-network

networks:
  cobweb-network:
    driver: bridge