services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cobweb-local-backend
    ports:
      - "8080:8080"
    env_file: "./backend/.env"
    networks:
      - cobweb-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cobweb-local-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - cobweb-network
    restart: unless-stopped

networks:
  cobweb-network:
    driver: bridge